---
title: "STAT 7670, HW1"
author: "D. Pluta"
date: '2026-01-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Due: 1/22

1. Problems from Anderson, Chapter 2:

  2.6, 2.7, 2.27, 2.28, 2.53
  
2. For $X = (X_1, X_2, \dots, X_p)$, find the conditional distribution 
for $X | \bar X = 0$, where $\bar X = \sum_{i = 1}^p X_i$.

3. Simulating Estimation Error for Covariances

We will consider simulating an $n \times p$ matrix $X \sim N(0, \Sigma)$ to 
estimate the covariance matrix $\Sigma$.  

For each setting, compute the MSE over 5000 iterations.

a.  *Vary n:* Let $p = 10$, and $\Sigma$ be the $p \times p$ identity matrix.  Simulate 
the MSE for $n = 25, 50, 100, 500, 1000$ and plot your results.

b. *Vary p:* Let $n = 100$ and $\Sigma$ be the $p \times p$ identity matrix.  Compute the MSE 
for $p = 10, 50, 100, 500, 1000$.

c. Repeat parts (a) and (b) with $\Sigma$ equal to the $AR(1)$ covariance matrix 
with unit variance and lag 1 correlation equal to $\rho = 1 / \sqrt{p}$.

4. a. Compute the Spectral Decomposition of $\Sigma = \begin{pmatrix} 2 & 0.3\\ 0.3 & 1\end{pmatrix}$.
b. Produce a plot of the ellipse corresponding to $\Sigma$.  Your plot should include vectors showing the major and minor axes of the ellipse.
c. Sample 250 points from $N(0, \Sigma)$.  Replicate the plot from (b), now including the sampled points. 